// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Week7.OrsolaLiccardo.Esercitazione;

#nullable disable

namespace Week7.OrsolaLiccardo.Esercitazione.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220114100100_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Week7.OrsolaLiccardo.Esercitazione.Models.Cliente", b =>
                {
                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .IsFixedLength();

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CodiceFiscale");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Week7.OrsolaLiccardo.Esercitazione.Models.Polizza", b =>
                {
                    b.Property<int>("numeroPolizza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .IsFixedLength();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("numeroPolizza"), 1L, 1);

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("nchar(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataStipula")
                        .HasColumnType("DateTime");

                    b.Property<double>("importoAssicurato")
                        .HasColumnType("float");

                    b.Property<double>("rataMensile")
                        .HasColumnType("float");

                    b.HasKey("numeroPolizza");

                    b.HasIndex("CodiceFiscale");

                    b.ToTable("Polizza", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Polizza");
                });

            modelBuilder.Entity("Week7.OrsolaLiccardo.Esercitazione.Models.Furto", b =>
                {
                    b.HasBaseType("Week7.OrsolaLiccardo.Esercitazione.Models.Polizza");

                    b.Property<int>("PercentuelCoperta")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Furto");
                });

            modelBuilder.Entity("Week7.OrsolaLiccardo.Esercitazione.Models.RCAuto", b =>
                {
                    b.HasBaseType("Week7.OrsolaLiccardo.Esercitazione.Models.Polizza");

                    b.Property<string>("Targa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cilindrata")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("RCAuto");
                });

            modelBuilder.Entity("Week7.OrsolaLiccardo.Esercitazione.Models.Vita", b =>
                {
                    b.HasBaseType("Week7.OrsolaLiccardo.Esercitazione.Models.Polizza");

                    b.Property<int>("AnniAssicurato")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Vita");
                });

            modelBuilder.Entity("Week7.OrsolaLiccardo.Esercitazione.Models.Polizza", b =>
                {
                    b.HasOne("Week7.OrsolaLiccardo.Esercitazione.Models.Cliente", "Cliente")
                        .WithMany("Polizze")
                        .HasForeignKey("CodiceFiscale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Week7.OrsolaLiccardo.Esercitazione.Models.Cliente", b =>
                {
                    b.Navigation("Polizze");
                });
#pragma warning restore 612, 618
        }
    }
}
